/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pizzaBillOrderV2;

import javax.swing.JTextField;

public class pizzaBillOrderV2 extends javax.swing.JFrame {

    /**
     * Creates new form pizzaBillOrderV2
     */
    double[] VegpriceList = {109, 259, 299, 299, 259, 299};
    int[] vegqty = new int[6];
    double[] nonvegpriceList = {359, 359, 249, 359, 359, 309};
    int[] nonvegqty = new int[6];
    boolean[] toplist = {false, false, false, false};
    int rate = 0;
    double discount = 0;
    double topamt = 0;
    int ordernumber = 1;

    double vegPrice = 0;
    String vegOrderList = "";
    double nonvegPrice = 0;
    String nonvegOrderList = "";

    public pizzaBillOrderV2() {
        initComponents();
        jRadioButton1.setSelected(true);
        jRadioButton7.setSelected(true);
        setResizable(false);
        setVisible(true);
        setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        ₹114 = new javax.swing.JLabel();
        ₹110 = new javax.swing.JLabel();
        ₹111 = new javax.swing.JLabel();
        ₹112 = new javax.swing.JLabel();
        ₹113 = new javax.swing.JLabel();
        ₹109 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        ₹115 = new javax.swing.JLabel();
        ₹116 = new javax.swing.JLabel();
        ₹117 = new javax.swing.JLabel();
        ₹118 = new javax.swing.JLabel();
        ₹119 = new javax.swing.JLabel();
        ₹120 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        orderNumberTxtf = new javax.swing.JTextField();
        customerNameTxtf = new javax.swing.JTextField();
        emailidtxtf = new javax.swing.JTextField();
        phoneNoTxtf = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jLabel30 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        clear = new javax.swing.JButton();
        GenerateBill = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jRadioButton6 = new javax.swing.JRadioButton();

        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("WAVE");
        jPanel2.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 630, 220, 30));

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("PANEER");
        jPanel2.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 630, 230, 30));

        ₹114.setBackground(new java.awt.Color(255, 255, 255));
        ₹114.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ₹114.setForeground(new java.awt.Color(255, 255, 255));
        ₹114.setText("₹299");
        jPanel2.add(₹114, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 600, 80, 20));

        ₹110.setBackground(new java.awt.Color(255, 255, 255));
        ₹110.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ₹110.setForeground(new java.awt.Color(255, 255, 255));
        ₹110.setText("₹259");
        jPanel2.add(₹110, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, -1, 20));

        ₹111.setBackground(new java.awt.Color(255, 255, 255));
        ₹111.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ₹111.setForeground(new java.awt.Color(255, 255, 255));
        ₹111.setText("₹299");
        jPanel2.add(₹111, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 280, 100, 20));

        ₹112.setBackground(new java.awt.Color(255, 255, 255));
        ₹112.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ₹112.setForeground(new java.awt.Color(255, 255, 255));
        ₹112.setText("₹259");
        jPanel2.add(₹112, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 600, 110, 20));

        ₹113.setBackground(new java.awt.Color(255, 255, 255));
        ₹113.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ₹113.setForeground(new java.awt.Color(255, 255, 255));
        ₹113.setText("₹299");
        jPanel2.add(₹113, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 600, -1, 20));

        ₹109.setBackground(new java.awt.Color(255, 255, 255));
        ₹109.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ₹109.setForeground(new java.awt.Color(255, 255, 255));
        ₹109.setText("₹109");
        jPanel2.add(₹109, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaBillOrderV2/Margherit.jpg"))); // NOI18N
        jLabel1.setIconTextGap(0);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 267, 266));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaBillOrderV2/Paneer_Makhni.jpg"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaBillOrderV2/Peppy_Paneer.jpg"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 270, 266));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaBillOrderV2/Deluxe_Veggie.jpg"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 336, -1, 259));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaBillOrderV2/Mexican_Green_Wave.jpg"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 336, -1, 259));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaBillOrderV2/IndianTandooriPaneer.jpg"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 340, 270, 260));
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        jTextField24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField24ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 610, 40, 30));

        jTextField25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField25ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 610, 40, 30));

        jTextField26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField26ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 40, 30));

        jTextField27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField27ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 40, 30));

        jTextField28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField28ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 290, 40, 30));

        jTextField29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField29ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 610, 40, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("PEPPY PANEER");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 160, 30));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("PANEER MAKHANI");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, 190, 30));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("VEGGIE DELUXE");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 610, 140, 30));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("MEXICAN GREEN");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 610, 220, 30));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("INDI TANDOORI");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 610, 230, 30));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("MARGHERITA");
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 130, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaBillOrderV2/jodie-morgan-v25z8P-CPB4-unsplash.jpg"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 680));

        jTabbedPane1.addTab("VEG SECTION", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ₹115.setBackground(new java.awt.Color(255, 255, 255));
        ₹115.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ₹115.setForeground(new java.awt.Color(255, 255, 255));
        ₹115.setText("₹359");
        jPanel3.add(₹115, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 50, 20));

        ₹116.setBackground(new java.awt.Color(255, 255, 255));
        ₹116.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ₹116.setForeground(new java.awt.Color(255, 255, 255));
        ₹116.setText("₹249");
        jPanel3.add(₹116, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 280, 50, 20));

        ₹117.setBackground(new java.awt.Color(255, 255, 255));
        ₹117.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ₹117.setForeground(new java.awt.Color(255, 255, 255));
        ₹117.setText("₹359");
        jPanel3.add(₹117, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 610, -1, 20));

        ₹118.setBackground(new java.awt.Color(255, 255, 255));
        ₹118.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ₹118.setForeground(new java.awt.Color(255, 255, 255));
        ₹118.setText("₹359");
        jPanel3.add(₹118, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 610, 70, 20));

        ₹119.setBackground(new java.awt.Color(255, 255, 255));
        ₹119.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ₹119.setForeground(new java.awt.Color(255, 255, 255));
        ₹119.setText("₹309");
        jPanel3.add(₹119, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 610, -1, 20));

        ₹120.setBackground(new java.awt.Color(255, 255, 255));
        ₹120.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ₹120.setForeground(new java.awt.Color(255, 255, 255));
        ₹120.setText("₹359");
        jPanel3.add(₹120, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, 20));

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("CHICKEN");
        jPanel3.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 310, 110, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon("D:\\JAVA\\pizzaBillingSystemFinal\\src\\pizzaBillOrderV2\\nonveg photos\\MicrosoftTeams-image_(13).png")); // NOI18N
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 270, 260));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("INDI TIKKI CHICKEN");
        jPanel3.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 190, 30));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("PEPPER BARBECUE");
        jPanel3.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, 180, 30));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("CHICKEN DOMINATOR");
        jPanel3.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 620, 200, 30));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("CHICKEN PEPPERONI");
        jPanel3.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 620, 190, 30));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("CHICKEN FIESTA");
        jPanel3.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 620, 170, 30));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("NON VEG SUPREME");
        jPanel3.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 170, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon("D:\\JAVA\\pizzaBillingSystemFinal\\src\\pizzaBillOrderV2\\nonveg photos\\MicrosoftTeams-image_(18).png")); // NOI18N
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 270, 260));

        jLabel13.setIcon(new javax.swing.ImageIcon("D:\\JAVA\\pizzaBillingSystemFinal\\src\\pizzaBillOrderV2\\nonveg photos\\MicrosoftTeams-image_(15).png")); // NOI18N
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 270, 260));

        jLabel14.setIcon(new javax.swing.ImageIcon("D:\\JAVA\\pizzaBillingSystemFinal\\src\\pizzaBillOrderV2\\nonveg photos\\MicrosoftTeams-image_(10).png")); // NOI18N
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 350, 270, 260));

        jLabel15.setIcon(new javax.swing.ImageIcon("D:\\JAVA\\pizzaBillingSystemFinal\\src\\pizzaBillOrderV2\\nonveg photos\\MicrosoftTeams-image_(11).png")); // NOI18N
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 270, 260));

        jLabel16.setIcon(new javax.swing.ImageIcon("D:\\JAVA\\pizzaBillingSystemFinal\\src\\pizzaBillOrderV2\\nonveg photos\\MicrosoftTeams-image_(20).png")); // NOI18N
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 270, 260));

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 620, 40, 30));

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 40, 30));

        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 290, 40, 30));

        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 620, 40, 30));

        jTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField17ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 620, 40, 30));

        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 40, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaBillOrderV2/(1)rodion-kutsaiev-EPwuZxdketc-unsplash.jpg"))); // NOI18N
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 680));

        jTabbedPane1.addTab("NON - VEG SECTION", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel19.setText("GST :");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, -1, -1));

        jLabel20.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel20.setText("ORDER NUMBER:");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel22.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel22.setText("EXTRA TOPPINGS");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, -1, -1));

        jLabel23.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel23.setText("CUSTOMER NAME :");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel24.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel24.setText("EMAIL ID :");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel25.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel25.setText("PIZZA PRICE :");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, -1));

        jLabel26.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel26.setText("AMOUNT :");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, -1, -1));

        jLabel27.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel27.setText("COST OF TOPPLINGS :");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, -1, -1));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField1.setEnabled(false);
        jPanel4.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 140, 190, -1));

        orderNumberTxtf.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        orderNumberTxtf.setEnabled(false);
        jPanel4.add(orderNumberTxtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 190, -1));
        jPanel4.add(customerNameTxtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 190, -1));

        emailidtxtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailidtxtfActionPerformed(evt);
            }
        });
        jPanel4.add(emailidtxtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 190, -1));

        phoneNoTxtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNoTxtfActionPerformed(evt);
            }
        });
        jPanel4.add(phoneNoTxtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 190, -1));

        jTextField7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField7.setEnabled(false);
        jPanel4.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 190, -1));

        jTextField8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField8.setEnabled(false);
        jPanel4.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, 190, -1));

        jTextField9.setText("8%");
        jTextField9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField9.setEnabled(false);
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, 190, -1));

        jLabel28.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel28.setText("COUPON AVAILABLE:");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jLabel29.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel29.setText("PIZZA BASE TYPE");
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jRadioButton1.setText("REGULAR");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        buttonGroup2.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jRadioButton2.setText("pizzaparty");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, -1, -1));

        buttonGroup2.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jRadioButton7.setText("none");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, -1, -1));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jRadioButton3.setText("CHEESE BURST");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jCheckBox13.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jCheckBox13.setText("TOMATO");
        jCheckBox13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox13ActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckBox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 320, -1, -1));

        jCheckBox14.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jCheckBox14.setText("ONION");
        jCheckBox14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox14ActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckBox14, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, -1, -1));

        jCheckBox15.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jCheckBox15.setText("BABY CORN");
        jCheckBox15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox15ActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckBox15, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, -1, -1));

        jCheckBox16.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jCheckBox16.setText("CHEESE");
        jCheckBox16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox16ActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckBox16, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 270, -1, -1));

        jLabel30.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel30.setText("PHONE NO :");
        jPanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jRadioButton4.setText("FRESH PAN PIZZA");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jRadioButton5.setText("cheesy80");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, -1, -1));

        clear.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel4.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 440, -1, -1));

        GenerateBill.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        GenerateBill.setText("GENERATE BILL");
        GenerateBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateBillActionPerformed(evt);
            }
        });
        jPanel4.add(GenerateBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 820, 150));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaBillOrderV2/(1)alex-lvrs-Uw0umuQnkpk-unsplash.jpg"))); // NOI18N
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 680));

        jRadioButton6.setText("jRadioButton6");
        jPanel4.add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 390, -1, -1));

        jTabbedPane1.addTab("BILLING SECTION", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 949, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox13ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox13.isSelected()) {
            toplist[3] = true;
        } else {
            toplist[3] = false;
        }
    }//GEN-LAST:event_jCheckBox13ActionPerformed

    private void jCheckBox14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox14ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox14.isSelected()) {
            toplist[0] = true;
        } else {
            toplist[0] = false;
        }

    }//GEN-LAST:event_jCheckBox14ActionPerformed

    private void jCheckBox15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox15ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox15.isSelected()) {
            toplist[2] = true;
        } else {
            toplist[2] = false;
        }
    }//GEN-LAST:event_jCheckBox15ActionPerformed

    private void jCheckBox16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox16ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox16.isSelected()) {
            toplist[1] = true;
        } else {
            toplist[1] = false;
        }
    }//GEN-LAST:event_jCheckBox16ActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // Clear
        vegPrice = 0;
        nonvegPrice = 0;
        rate = 0;
        discount = 0;
        topamt = 0;
        jRadioButton1.setSelected(true);
        jRadioButton7.setSelected(true);
        jCheckBox13.setSelected(false);
        jCheckBox14.setSelected(false);
        jCheckBox15.setSelected(false);
        jCheckBox16.setSelected(false);
        jTextField10.setText("");
        jTextField11.setText("");
        jTextField15.setText("");
        jTextField16.setText("");
        jTextField17.setText("");
        jTextField18.setText("");
        jTextField24.setText("");
        jTextField25.setText("");
        jTextField26.setText("");
        jTextField27.setText("");
        jTextField28.setText("");
        jTextField29.setText("");
        jTextField1.setText("");
        orderNumberTxtf.setText("");
        customerNameTxtf.setText("");
        emailidtxtf.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextArea1.setText("");
        phoneNoTxtf.setText("");
        for (int i = 0; i < 4; i++) {
            toplist[i] = false;
        }
        for (int j = 0; j < 6; j++) {
            vegqty[j] = 0;
            nonvegqty[j] = 0;
        }
    }//GEN-LAST:event_clearActionPerformed

    private void GenerateBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateBillActionPerformed
        // TODO add your handling code here:
        eventButtonClicked();
        vegPrice = 0;
        nonvegPrice = 0;
        rate = 0;
        discount = 0;
        topamt = 0;
        ordernumber++;
    }//GEN-LAST:event_GenerateBillActionPerformed

    public String eventButtonClicked() {
        int orderno = ordernumber;
        orderNumberTxtf.setText(orderno + "");
        String custname
                = customerNameTxtf.getText();
        String emailid
                = emailidtxtf.getText();

        if (!emailid.endsWith("@gmail.com")) {
            emailid = "**InvalidEmailId";
        }

        String phoneNo = phoneNoTxtf.getText();
        boolean isNumeric = phoneNo.chars().allMatch(Character::isDigit);
        if (isNumeric && phoneNo.length() == 10) {

        } else {
            phoneNo = "**InvalidPhoneNo";
            jTextArea1.setText("Bill Not Generated");
            return jTextArea1.getText();
        }

        for (int i = 0; i < 6; i++) {
            vegPrice += VegpriceList[i] * vegqty[i];
        }
        for (int i = 0; i < 6; i++) {
            nonvegPrice += nonvegpriceList[i] * nonvegqty[i];
        }

        // Displays rate of selected pizza
        // type in TextField
        // combining nonveg and veg prices to pizza base price
        rate = 0;
        rate += nonvegPrice + vegPrice;

        jTextField7.setText(
                "" + rate);

        // Pizza toppings conditions
        topamt = 0;
        if (toplist[0] == true) {
            topamt = 60;
        }
        if (toplist[1] == true) {
            topamt = topamt + 30;
        }
        if (toplist[2] == true) {
            topamt = topamt + 40;
        }
        if (toplist[3] == true) {
            topamt = topamt + 50;
        }

        // Displays total amount of
        // selected pizza toppings in TextField
        jTextField8.setText(
                ""
                + topamt);

        // Total amount is calculated
        double payable
                = (rate) + topamt;
        payable -= discount * payable;
        double gst = 8;
        double totalpayable = Math.round(payable * (1 + gst / 100));
        jTextField1.setText("" + totalpayable);

        // vegorderlist
        // nonvegOrderList
        // Displays order details
        jTextArea1
                .setText(
                        "Hello" + custname + ", Your Order Id is: "
                        + orderno
                        + "\nEmail ID: " + emailid
                        + "\nPhone number: " + phoneNo
                        + "\nAMOUNT PAYABLE IS: " + totalpayable
                        + "\nThe list of items ordered are:"
                        + setnonvegOrderList() + setvegOrderList());

        vegPrice = 0;
        nonvegPrice = 0;
        return jTextArea1.getText();
    }

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
        discount = 0.08;
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        discount = 0.10;
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
        nonvegqty[0] = Integer.parseInt(jTextField11.getText());
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField24ActionPerformed
        // TODO add your handling code here:
        vegqty[5] = Integer.parseInt(jTextField24.getText());
    }//GEN-LAST:event_jTextField24ActionPerformed

    private void jTextField25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField25ActionPerformed
        // TODO add your handling code here:
        vegqty[3] = Integer.parseInt(jTextField25.getText());

    }//GEN-LAST:event_jTextField25ActionPerformed

    private void jTextField26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField26ActionPerformed
        // TODO add your handling code here:
        vegqty[0] = Integer.parseInt(jTextField26.getText());

    }//GEN-LAST:event_jTextField26ActionPerformed

    private void jTextField27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField27ActionPerformed
        // TODO add your handling code here:
        vegqty[1] = Integer.parseInt(jTextField27.getText());

    }//GEN-LAST:event_jTextField27ActionPerformed

    private void jTextField28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField28ActionPerformed
        // TODO add your handling code here:
        vegqty[2] = Integer.parseInt(jTextField28.getText());

    }//GEN-LAST:event_jTextField28ActionPerformed

    private void jTextField29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField29ActionPerformed
        // TODO add your handling code here:
        vegqty[4] = Integer.parseInt(jTextField29.getText());

    }//GEN-LAST:event_jTextField29ActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
        nonvegqty[1] = Integer.parseInt(jTextField18.getText());
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
        nonvegqty[2] = Integer.parseInt(jTextField15.getText());
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
        nonvegqty[3] = Integer.parseInt(jTextField16.getText());
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
        nonvegqty[4] = Integer.parseInt(jTextField10.getText());
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        // TODO add your handling code here:
        nonvegqty[5] = Integer.parseInt(jTextField17.getText());
    }//GEN-LAST:event_jTextField17ActionPerformed

    private void phoneNoTxtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNoTxtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNoTxtfActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
        discount = 0;
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void emailidtxtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailidtxtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailidtxtfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pizzaBillOrderV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pizzaBillOrderV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pizzaBillOrderV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pizzaBillOrderV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        new pizzaBillOrderV2();
    }

    public String setvegOrderList() {
        vegOrderList = "";
        if (vegqty[0] > 0) {
            vegOrderList += "\nMargherita veg pizza :" + vegqty[0];
        }
        if (vegqty[1] > 0) {
            vegOrderList += "\nPepper Paneer veg pizza :" + vegqty[1];
        }
        if (vegqty[2] > 0) {
            vegOrderList += "\nPaneer Makhani veg pizza :" + vegqty[2];
        }
        if (vegqty[3] > 0) {
            vegOrderList += "\nVeggie Deluxe veg pizza :" + vegqty[3];
        }
        if (vegqty[4] > 0) {
            vegOrderList += "\nMexican Green Wave veg pizza :" + vegqty[4];
        }
        if (vegqty[5] > 0) {
            vegOrderList += "\nIndi Tandoori Paneer veg pizza :" + vegqty[5];
        }
        return vegOrderList;
    }

    public String setnonvegOrderList() {
        nonvegOrderList = "";
        if (nonvegqty[0] > 0) {
            nonvegOrderList += "\nNon veg Supreme nonveg pizza :" + nonvegqty[0];
        }
        if (nonvegqty[1] > 0) {
            nonvegOrderList += "\nIndi Tikki Chicken nonveg pizza :" + nonvegqty[1];
        }
        if (nonvegqty[2] > 0) {
            nonvegOrderList += "\nPepper Barbecue Chicken nonveg pizza :" + nonvegqty[2];
        }
        if (nonvegqty[3] > 0) {
            nonvegOrderList += "\nChicken Dominator nonveg pizza :" + nonvegqty[3];
        }
        if (nonvegqty[4] > 0) {
            nonvegOrderList += "\nChicken Pepperoni nonveg pizza :" + nonvegqty[4];
        }
        if (nonvegqty[5] > 0) {
            nonvegOrderList += "\nChicken Fiesta nonveg pizza :" + nonvegqty[5];
        }
        return nonvegOrderList;
    }

    public void setCustomerNameTxtf(JTextField customerNameTxtf) {
        this.customerNameTxtf = customerNameTxtf;
    }

    public void setEmailidtxtf(JTextField emailidtxtf) {
        this.emailidtxtf = emailidtxtf;
    }

    public void setOrderNumberTxtf(JTextField orderNumberTxtf) {

    }

    public void setPhoneNoTxtf(JTextField phoneNoTxtf) {
        this.phoneNoTxtf = phoneNoTxtf;
    }

    public void setvegqty(int[] qty) {
        this.vegqty[0] = qty[0];
        this.vegqty[1] = qty[1];
        this.vegqty[2] = qty[2];
        this.vegqty[3] = qty[3];
        this.vegqty[4] = qty[4];
        this.vegqty[5] = qty[5];
    }

    public void setnonvegqty(int[] qty) {
        this.nonvegqty[0] = qty[0];
        this.nonvegqty[1] = qty[1];
        this.nonvegqty[2] = qty[2];
        this.nonvegqty[3] = qty[3];
        this.nonvegqty[4] = qty[4];
        this.nonvegqty[5] = qty[5];
    }

    public void setpizzabasetype(int n) {
    }

    public void setdiscount(double discount) {
        this.discount = discount;
    }

    public String getBill() {

        return jTextArea1.getText();
    }

    public void settoppings(boolean[] toppings) {
        toplist[0] = toppings[0];
        toplist[1] = toppings[1];
        toplist[2] = toppings[2];
        toplist[3] = toppings[3];
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GenerateBill;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton clear;
    private javax.swing.JTextField customerNameTxtf;
    private javax.swing.JTextField emailidtxtf;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField orderNumberTxtf;
    private javax.swing.JTextField phoneNoTxtf;
    private javax.swing.JLabel ₹109;
    private javax.swing.JLabel ₹110;
    private javax.swing.JLabel ₹111;
    private javax.swing.JLabel ₹112;
    private javax.swing.JLabel ₹113;
    private javax.swing.JLabel ₹114;
    private javax.swing.JLabel ₹115;
    private javax.swing.JLabel ₹116;
    private javax.swing.JLabel ₹117;
    private javax.swing.JLabel ₹118;
    private javax.swing.JLabel ₹119;
    private javax.swing.JLabel ₹120;
    // End of variables declaration//GEN-END:variables
}
